---
deployment:
  tasks:
    - /bin/cp -R dist/public/* /home/angelin/guild.angelin.dev
    - /bin/cp -R dist/src/* /home/angelin/guild
    - cd /home/angelin/guild && php artisan migrate:fresh --seed